name: Reusable Github Actions

# run-name: Github Reusable Workflow

on:
  workflow_call:

jobs:
  Reusable-workflow:
    runs-on: 
      - self-hosted
      - label-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
